-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Usr CASCADE;
DROP TABLE IF EXISTS Wine CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS ReviewTag CASCADE;
